name = "SphealCraft Forever"
author = "it's blur"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84e63242a6f3d6364524a513f481d1efc2c6ac026eeb5fd270bcfc6d4f7d6b44"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
