name = "SphealCraft Forever"
author = "it's blur"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef797687d29764413a28e02fd1950462d0076d0a9928aa2ccaaf594814c5d825"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
