name = "SphealCraft Forever"
author = "it's blur"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "845b09c76549650610f69d5ec62ff391c6c1cce29dd79982f7ec26fdc86571c8"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
